### ISSUE TITLE
People Skill sending 'BadRequest' error message

### ISSUE THREAD

**Issue by bensonjm** [microsoft/botframework-components#1319]
## Describe the bug

The People Skill sends a 'BadRequest' message after sending a list of users it found.

## Version

Composer version 2.1.2
SDK version 4.15.2

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills.
2. Enter 'Priya's manager' (or any common name e.g. John)
3. It will return a list of entries for since it's not able to find a unique user
4. After it returns the list it throws an error and the list buttons don't work

## Expected behavior

The list should work and the error shouldn't be shown to the user

## Screenshots

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/48541415/160886518-12b0f8f9-1a4f-4836-987c-7b42e9eeef40.png">

## Additional context

When clicking on 'Peers' though it shows a list card and the error doesn't occur. It's when it's retrieving a list of users for an intent reply that this error occurs.

**Comment by ramfattah** [comment]
Hello @bensonjm, I'm investigating this.

**Comment by goabacus** [comment]
Same issue. Only happening in MS-Teams.

**Comment by ramfattah** [comment]
@bensonjm @goabacus -- thank you for your patience, we are investigating this.

**Comment by bensonjm** [comment]
@ramfattah, found another scenario with this error.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/48541415/162556682-34c14a47-eb4a-41fa-94d0-936bbbae65f8.png">
I tried to get my colleague's peers (3 pages/cards). It sent the first card/page with 5 users however when I go the 2 page it gave me the same error. But if I click the arrow again it goes to the last page 3 and returns the card. Page 2 card fails.

PEOPLE BOT -->
Category: Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.CoreBotAdapter
EventId: 0
ConnectionId: xxxxx
RequestId: xxxxx:xxxxx
RequestPath: /api/messages
SpanId: xxxxx
TraceId: xxxxx
ParentId: xxxxx
ActionId: xxxxx
ActionName: People.Controllers.BotController.PostAsync (People)

[OnTurnError] unhandled error : InputDialog is missing Prompt.

Exception: 
System.InvalidOperationException: InputDialog is missing Prompt.
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog.OnRenderPromptAsync(DialogContext dc, InputState state, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.OAuthInput.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialogBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.SetSpeakMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)




CORE/ROOT BOT -->
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
ConnectionId: xxxxx
RequestId: xxxxx:xxxxx
RequestPath: /api/messages
SpanId: xxxxx
TraceId: xxxxx
ParentId: xxxxx

Connection id "xxxxx", Request id "xxxxx:xxxxx": An unhandled exception was thrown by the application.

Exception: 
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Microsoft.Bot.Connector.Authentication.JwtTokenExtractor.ValidateTokenAsync(String jwtToken, String channelId, String[] requiredEndorsements)
   at Microsoft.Bot.Connector.Authentication.JwtTokenExtractor.GetIdentityAsync(String scheme, String parameter, String channelId, String[] requiredEndorsements)
   at Microsoft.Bot.Connector.Authentication.JwtTokenExtractor.GetIdentityAsync(String authorizationHeader, String channelId, String[] requiredEndorsements)
   at Microsoft.Bot.Connector.Authentication.ChannelValidation.AuthenticateChannelToken(String authHeader, ICredentialProvider credentials, HttpClient httpClient, String channelId, AuthenticationConfiguration authConfig)
   at Microsoft.Bot.Connector.Authentication.ChannelValidation.AuthenticateChannelToken(String authHeader, ICredentialProvider credentials, String serviceUrl, HttpClient httpClient, String channelId, AuthenticationConfiguration authConfig)
   at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.AuthenticateTokenAsync(String authHeader, ICredentialProvider credentials, IChannelProvider channelProvider, String channelId, AuthenticationConfiguration authConfig, String serviceUrl, HttpClient httpClient)
   at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.ValidateAuthHeader(String authHeader, ICredentialProvider credentials, IChannelProvider channelProvider, String channelId, AuthenticationConfiguration authConfig, String serviceUrl, HttpClient httpClient)
   at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.AuthenticateRequest(IActivity activity, String authHeader, ICredentialProvider credentials, IChannelProvider provider, AuthenticationConfiguration authConfig, HttpClient httpClient)
   at Microsoft.Bot.Connector.Authentication.BuiltinBotFrameworkAuthentication.AuthenticateRequestAsync(Activity activity, String authHeader, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at LillyEnterpriseAssistant.Controllers.BotController.PostAsync(String route) in /Users/C283281/Workspace/Repos/Lilly/gis-lilly-enterprise-assistant/LillyEnterpriseAssistant/LillyEnterpriseAssistant/Controllers/BotController.cs:line 67
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by ramfattah** [comment]
@bensonjm 

Thank you for your patience. This is being investigated.

**Comment by ramfattah** [comment]
Hey @bensonjm

Are you able to share a screenshot of your People skill `ListDialog` foreach action? 

Ex:
![image](https://user-images.githubusercontent.com/38049078/164106326-2ce2c0a9-79a4-4652-bf88-a30c56512913.png)

#

Could you perhaps try setting the index and value properties to:
     
   * Index property: `turn.listDialogForeach.index`
   * Value property: `turn.listDialogForeach.value`

**Comment by bensonjm** [comment]
@ramfattah

This was ListDialog before the change you suggested.
<img width="1723" alt="Screen Shot 2022-04-20 at 10 19 09 AM" src="https://user-images.githubusercontent.com/48541415/164222846-50cb681e-83b2-41ec-ae21-2ef2538a8394.png">

After making the changes you suggested, I'm getting the below error:
To reproduce, ask for someone's peers e.g. John's peers

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/48541415/164222939-7941c958-d979-4cdf-bac9-f82b365865a5.png">

<img width="1332" alt="Screen Shot 2022-04-20 at 5 00 17 PM" src="https://user-images.githubusercontent.com/48541415/164223038-43c0ce4b-a5cb-4ea4-b0cb-09764bb366ef.png">

<img width="692" alt="Screen Shot 2022-04-20 at 5 00 24 PM" src="https://user-images.githubusercontent.com/48541415/164223066-81768405-cc05-473b-9fc7-b1d88346944a.png">

**Comment by ramfattah** [comment]
Update: I'm able to reproduce this issue

Here are the steps I took:
* Created an Enterprise Assistant Template from the following documentation https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-tutorial
* Start all 3 bots to run from my local machine
* Opened the root bot (EnterpriseAssistant) in Emulator.
* Followed the initial dialog flow, then I typed `John's manager` 
* Got presented with the same error as the customer `Operation returned an invalid status code ‘BadRequest’`

![image](https://user-images.githubusercontent.com/38049078/164282322-f49e8403-913a-4669-a973-af89e4a32099.png)

**Comment by ramfattah** [comment]
https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-tutorial

**Comment by ramfattah** [comment]
Closing with PR https://github.com/microsoft/botframework-components/pull/1326
