### ISSUE TITLE
Error when I load existing bot

### ISSUE THREAD

**Issue by davidcg96** [microsoft/botframework-components#1500]
**Hi,
I have created a empty bot in Framework composer and I export this bot like zip.
I open the framework composer again and I select open existing bot.
I  select the project exported and this was opened well.
when i try to test the bot appear errors:

Error occurred building the bot**

Message:
Command failed: dotnet user-secrets init --project Pruebagit_export.csproj
Command failed : The project file 'C:\Users\david.calabres\Desktop\Codigos\Tirea\RepositorioBucket\tirea_bot\Pruebagit_export\Pruebagit_export.csproj' does not exist.
Command:
dotnet user-secrets init --project Pruebagit_export.csproj
Stack Trace:
Error: Command failed: dotnet user-secrets init --project Pruebagit_export.csproj
Command failed : The project file 

I have two questions about this:
     1- ¿How can I share my bot in github for my teamwork?
     2- How can I fix this error?

**Comment by ramfattah** [comment]
Hi @davidcg96,

Thank you for bringing this issue to our attention. I was able to replicate the error using Composer version 2.1.2.

Here's the detailed sequence of steps I followed to repro:
1. Firstly, I created a bot using C# in Composer.
2. Once the bot was ready, I exported it as a .zip file.
4. I then located the newly exported .zip file on my system.
5. I unzipped this file to access the exported bot.
6. Imported the unzipped bot back into Composer.
7. Finally I started the bot in Composer and ran into the following error:

```
rror occurred building the bot

Message:
Command failed: dotnet user-secrets init --project ExportedBot_export.csproj
Command failed : The project file 'C:\Users\v-fattahram\Downloads\ExportedBot_export\ExportedBot_export.csproj' does not exist.
Command:
dotnet user-secrets init --project ExportedBot_export.csproj
Stack Trace:
Error: Command failed: dotnet user-secrets init --project ExportedBot_export.csproj
Command failed : The project file 'C:\Users\v-fattahram\Downloads\ExportedBot_export\ExportedBot_export.csproj' does not exist.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
System.IO.FileNotFoundException: The project file 'C:\Users\v-fattahram\Downloads\ExportedBot_export\ExportedBot_export.csproj' does not exist.
   at MsBuildProjectFinder.FindMsBuildProject(String project)
   at UserSecretsCreator.ResolveProjectPath(String name, String path)
   at UserSecretsCreator.CreateUserSecretsId(IReporter reporter, String project, String workingDirectory, String overrideId)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommandFactory.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Program.RunInternal(String[] args)
   at Microsoft.Extensions.SecretManager.Tools.Program.TryRun(String[] args, Int32& returnCode)
Killed:
Code:
1
Stderr:
Command failed : The project file 'C:\Users\v-fattahram\Downloads\ExportedBot_export\ExportedBot_export.csproj' does not exist.
```

**Comment by ramfattah** [comment]
Hey @ceciliaavila, 

I have successfully replicated the problem reported. Assigning this to you for now.

Please let me know if you have any question.
Thanks!

**Comment by davidcg96** [comment]
@ceciliaavila @ramfattah  Thanks when fix the error, can you notice me when the steps for reply?. thanks

**Comment by ceciliaavila** [comment]
Hi @ramfattah, @davidcg96, we added this issue to our backlog. We'll start working on it this week and let you know as soon as we have updates.
Thanks.

**Comment by ramfattah** [comment]
Thanks for your effort @ceciliaavila.

@davidcg96, please find @ceciliaavila suggestion above for a workaround.

**Comment by davidcg96** [comment]
perfect, with this indications, the bot work.
